### ISSUE TITLE
Add toolbar button

### ISSUE THREAD

**Issue by softashell** [Rainyan/jump-to-audible-tabs#5]
Jumping to last audible tab would be more comfy to use as a button in toolbar. Context menu is pretty cluttered already and on some pages you can't even open it since some JS is replacing it. The only consistent place I found to use it was tab bar.

I could probably do this myself and open PR.

**Comment by Rainyan** [comment]
This sounds like a good idea. If you have the time to make a PR, it'd be very welcome.
